import datetime
from typing import List
from sqlmodel import Session, select
from src.database import engine
from src.models import NewsFlash, Report
from src.notifier import send_feishu_summary
from src.logger import setup_logger

logger = setup_logger("sentinel.report")

def get_news_in_range(start_time: datetime.datetime, end_time: datetime.datetime) -> List[NewsFlash]:
    """
    查询指定时间范围内的所有新闻
    """
    with Session(engine) as session:
        statement = select(NewsFlash).where(
            NewsFlash.pub_time >= start_time,
            NewsFlash.pub_time <= end_time
        ).order_by(NewsFlash.pub_time.desc())
        results = session.exec(statement).all()
        return list(results)

def _generate_report_payload(news_list: List[NewsFlash]) -> List[dict]:
    """
    将 DB 模型转换为 Notifier 需要的字典格式
    """
    payload = []
    for news in news_list:
        payload.append({
            "title": news.title,
            "url": news.url,
            "content": news.content,
            "tags": news.tags
        })
    return payload

def _generate_html_report(title: str, start_time: datetime.datetime, end_time: datetime.datetime, news_list: List[NewsFlash]) -> str:
    """
    生成简单的静态 HTML 报表内容
    """
    html_items = []
    for news in news_list:
        tags_html = ""
        if news.tags:
            for tag in news.tags.split(','):
                tags_html += f'<span style="background:#fee2e2;color:#991b1b;padding:2px 6px;border-radius:4px;font-size:0.8em;margin-right:5px;">{tag}</span>'
        
        item_html = f"""
        <div style="border-bottom:1px solid #eee; padding:15px 0;">
            <div style="font-size:0.85em; color:#666; margin-bottom:5px;">
                {news.pub_time.strftime('%Y-%m-%d %H:%M')} | <span style="text-transform:uppercase;">{news.source}</span>
            </div>
            <a href="{news.url}" target="_blank" style="font-size:1.1em; font-weight:bold; color:#333; text-decoration:none; display:block; margin-bottom:8px;">{news.title}</a>
            <div style="line-height:1.5; color:#444; font-size:0.95em;">{news.content}</div>
            <div style="margin-top:8px;">{tags_html}</div>
        </div>
        """
        html_items.append(item_html)
    
    joined_items = "\n".join(html_items)
    
    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="utf-8">
    <title>{title}</title>
    </head>
    <body style="font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6;">
        <h1 style="border-bottom: 2px solid #10b981; padding-bottom: 10px;">{title}</h1>
        <p style="color:#666;">统计周期: {start_time.strftime('%Y-%m-%d %H:%M')} ~ {end_time.strftime('%Y-%m-%d %H:%M')}</p>
        <p>共收录 {len(news_list)} 条高价值情报。</p>
        <hr style="border:0; border-top:1px solid #eee; margin:20px 0;">
        
        {joined_items}
        
        <footer style="margin-top:40px; text-align:center; font-size:0.8em; color:#999;">
            Generated by Sentinel System
        </footer>
    </body>
    </html>
    """
    return full_html

def _save_report(session: Session, report_type: str, start: datetime.datetime, end: datetime.datetime, html: str):
    """保存报表到数据库"""
    try:
        report = Report(
            type=report_type,
            period_start=start,
            period_end=end,
            content_html=html,
            created_at=datetime.datetime.now()
        )
        session.add(report)
        session.commit()
        logger.info(f"报表已归档: {report_type} ({report.id})")
    except Exception as e:
        logger.error(f"报表归档失败: {e}")

def run_daily_report():
    """生成日报任务"""
    now = datetime.datetime.now()
    yesterday = now - datetime.timedelta(days=1)
    
    logger.info(f"开始生成日报 ({yesterday.strftime('%m-%d %H:%M')} ~ {now.strftime('%m-%d %H:%M')})")
    
    news_list = get_news_in_range(yesterday, now)
    if not news_list:
        logger.info("周期内无新闻数据，跳过日报推送。")
        return

    logger.info(f"查询到 {len(news_list)} 条记录，准备处理...")
    
    # 1. 发送飞书
    items_payload = _generate_report_payload(news_list)
    title = f"Sentinel 日报 ({now.strftime('%Y-%m-%d')})"
    
    is_sent = send_feishu_summary(items_payload, title_prefix="Sentinel 日报")
    
    # 2. 无论推送是否成功，都尝试生成并保存归档 (作为记录)
    html_content = _generate_html_report(title, yesterday, now, news_list)
    
    with Session(engine) as session:
        # 保存归档
        _save_report(session, 'daily', yesterday, now, html_content)
        
        # 标记状态 (如果推送成功)
        if is_sent:
            update_count = 0
            for news in news_list:
                db_news = session.get(NewsFlash, news.id)
                if db_news:
                    db_news.in_daily_report = True
                    session.add(db_news)
                    update_count += 1
            session.commit()
            logger.info(f"日报推送成功！已标记 {update_count} 条记录。")
        else:
            logger.warning("日报推送失败 (Webhook 请求异常或未配置)，但在本地已尝试归档。")

def run_weekly_report():
    """生成周报任务"""
    now = datetime.datetime.now()
    last_week = now - datetime.timedelta(days=7)
    
    logger.info(f"开始生成周报 ({last_week.strftime('%m-%d %H:%M')} ~ {now.strftime('%m-%d %H:%M')})")
    
    news_list = get_news_in_range(last_week, now)
    if not news_list:
        logger.info("周期内无新闻数据，跳过周报推送。")
        return

    logger.info(f"查询到 {len(news_list)} 条记录，准备处理...")
    
    # 1. 发送飞书
    items_payload = _generate_report_payload(news_list)
    title = f"Sentinel 周报 ({last_week.strftime('%m-%d')} ~ {now.strftime('%m-%d')})"
    
    is_sent = send_feishu_summary(items_payload, title_prefix="Sentinel 周报")
    
    # 2. 生成归档
    html_content = _generate_html_report(title, last_week, now, news_list)
    
    with Session(engine) as session:
        # 保存归档
        _save_report(session, 'weekly', last_week, now, html_content)
        
        if is_sent:
            update_count = 0
            for news in news_list:
                db_news = session.get(NewsFlash, news.id)
                if db_news:
                    db_news.in_weekly_report = True
                    session.add(db_news)
                    update_count += 1
            session.commit()
            logger.info(f"周报推送成功！已标记 {update_count} 条记录。")
        else:
            logger.warning("周报推送失败。")
